dataSource:
  type: stub
  sortBy: intensity
  locations:
    preset: gcp
taints:
  type: worst
  effect: PreferNoSchedule
  shouldTaintOnlyLocation: true
labels:
  type: binary
  thresholds:
    acceptable:
      value: 50