dataSource:
  type: CAAPI
  sortBy: currentIntensity
taints:
  type: worst
  effect: PreferNoSchedule
  shouldTaintOnlyLocation: true
labels:
  type: binary
  thresholds:
    acceptable:
      value: 50