# tolerates the taint greensoftware.foundation/carbon-intensity -> can be scheduled on tainted nodes
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  tolerations:
  - key: greensoftware.foundation/carbon-intensity
    operator: Equal
    value: high
    effect: NoSchedule
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox
    command:
    - echo
    - hi