apiVersion: v1
kind: ConfigMap
metadata:
  name: cake-node-analyzer
data:
  config.yaml: |
{{ .Values.policy | toYaml | indent 4 }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cake-node-analyzer
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Replace
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cake-node-analyzer
          restartPolicy: Never
          {{ if .Values.tolerations }}
          tolerations: {{ toYaml .Values.tolerations | nindent 12 }}
          {{ end }}
          containers:
          - name: main
            image: {{ .Values.image }}
            imagePullPolicy: Always
            resources: {{ toYaml .Values.resources | nindent 14 }}
            volumeMounts:
              - mountPath: /workdir/config.yaml
                name: config-volume
                subPath: config.yaml
            args:
            - hello
          volumes:
            - name: config-volume
              configMap:
                name: cake-node-analyzer