apiVersion: v1
kind: ServiceAccount
metadata:
  name: cake-node-analyzer
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cake-node-analyzer
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cake-node-analyzer
subjects:
- kind: ServiceAccount
  name: cake-node-analyzer
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cake-node-analyzer
  apiGroup: rbac.authorization.k8s.io