apiVersion: v1
kind: ConfigMap
metadata:
  name: carbon-aware-policy-config
data:
  config.yaml: |
{{ .Values.policy | toYaml | indent 4 }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: carbon-aware-node-manager
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Replace
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: carbon-aware-node-manager
          restartPolicy: Never
          containers:
          - name: cao
            image: {{ .Values.image }}
            imagePullPolicy: Always
            resources: {{ toYaml .Values.resources | nindent 14 }}
            volumeMounts:
              - mountPath: /workdir/config.yaml
                name: config-volume
                subPath: config.yaml
            args:
            - hello
          volumes:
            - name: config-volume
              configMap:
                name: carbon-aware-policy-config