apiVersion: v1
kind: ServiceAccount
metadata:
  name: carbon-aware-node-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: carbon-aware-node-manager
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: carbon-aware-node-manager
subjects:
- kind: ServiceAccount
  name: carbon-aware-node-manager
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: carbon-aware-node-manager
  apiGroup: rbac.authorization.k8s.io